name: te_escucha
description: Inea te Escucha.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.4.0
  http: ^0.13.4
  material_dialogs: ^1.1.4
  flutter_localizations:
    sdk: flutter
  geolocator: ^9.0.2
  google_maps: ^6.3.0
  animate_do: ^3.0.2
  google_sign_in_web: ^0.12.0+3
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  firebase_core: ^2.15.1
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  oauth2_client: ^3.2.1
  google_identity_services_web: ^0.2.1+1
  google_sign_in_platform_interface: ^2.4.2
  universal_html: ^2.2.4
  shared_preferences: ^2.2.1
  flutter_markdown: ^0.6.17+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/estatus/
    - assets/servicios/
    - assets/tramites/
    - assets/group/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #